[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "httpx>=0.28.1",
    "networkx>=3.4.2",
    "numpy>=2.2.3",
    "pytest>=8.3.4",
    "scipy>=1.15.2",
    "uvicorn>=0.34.0",
]
